// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/humekaneza-refresh/Current.tsx": () => import("../components/mockups/humekaneza-refresh/Current.tsx"),
  "./components/mockups/humekaneza-refresh/Refresh.tsx": () => import("../components/mockups/humekaneza-refresh/Refresh.tsx")
};
